/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berana;

import static berana.Ulogin.*;
import java.awt.*;
import java.io.File;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Uhome extends javax.swing.JFrame {
   boolean input = false;
   String tableValue = null;
   String followedEmail;
   String studyTips [] = {"Pick a place and time","Study every day","Plan your time","Review and revise","Take breaks","Ask for help"};
   String s;
   String path=null;
   CardLayout cardLayout;
   public void view(){
        setVisible(false);
    }
   public void refreshHome(){
       HomeUser huser= new HomeUser();
       huser.homeUser(email, pass);
       huser.followers(email);
       huser.following(email);
       jLabel2.setText("Welcome back "+huser.username);
       jLabel9.setText(huser.postNum);
       jLabel11.setText(huser.followers);
       jLabel12.setText(huser.following);
       PopulatePostTable ps = new PopulatePostTable();
       ps.populate(email,tableValue,jTable1,input);
       PictureUser pu = new PictureUser();
       pu.getPicture(email, jLabel6);
   }
    
    public Uhome() {
        initComponents();
        refreshHome();
        setLocationRelativeTo(null);
        jLabel16.setText(studyTips[new Random().nextInt(studyTips.length)]); 
        cardLayout = (CardLayout)(contentbar.getLayout());
        //jComboBox1.setVisible(false);
        jScrollPane6.setVisible(false);
        kButton7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidebar = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Button2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Button3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Button4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        contentbar = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_Close = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        kButton4 = new keeptoo.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dashboard = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        btn_Close1 = new javax.swing.JLabel();
        kButton6 = new keeptoo.KButton();
        kButton7 = new keeptoo.KButton();
        kButton8 = new keeptoo.KButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        kButton5 = new keeptoo.KButton();
        jLabel31 = new javax.swing.JLabel();
        kButton10 = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        kButton12 = new keeptoo.KButton();
        profile = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        kButton11 = new keeptoo.KButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
        });
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button1.setBackground(new java.awt.Color(205, 136, 205));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 77, 184));
        jLabel1.setText("Home");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_home_page_25px.png"))); // NOI18N
        jLabel19.setText("jLabel19");

        javax.swing.GroupLayout Button1Layout = new javax.swing.GroupLayout(Button1);
        Button1.setLayout(Button1Layout);
        Button1Layout.setHorizontalGroup(
            Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        Button1Layout.setVerticalGroup(
            Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 149, 220, -1));

        Button2.setBackground(new java.awt.Color(255, 255, 255));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 83, 150));
        jLabel3.setText("Dashboard");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_content_25px.png"))); // NOI18N
        jLabel21.setText("jLabel19");

        javax.swing.GroupLayout Button2Layout = new javax.swing.GroupLayout(Button2);
        Button2.setLayout(Button2Layout);
        Button2Layout.setHorizontalGroup(
            Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        Button2Layout.setVerticalGroup(
            Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 211, 220, -1));

        Button3.setBackground(new java.awt.Color(255, 255, 255));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button3MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 83, 150));
        jLabel4.setText("Profile");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_edit_profile_25px.png"))); // NOI18N
        jLabel20.setText("jLabel19");

        javax.swing.GroupLayout Button3Layout = new javax.swing.GroupLayout(Button3);
        Button3.setLayout(Button3Layout);
        Button3Layout.setHorizontalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        Button3Layout.setVerticalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, 220, -1));

        Button4.setBackground(new java.awt.Color(255, 255, 255));
        Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 83, 150));
        jLabel5.setText("Logout");

        javax.swing.GroupLayout Button4Layout = new javax.swing.GroupLayout(Button4);
        Button4.setLayout(Button4Layout);
        Button4Layout.setHorizontalGroup(
            Button4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel5)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        Button4Layout.setVerticalGroup(
            Button4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 220, -1));

        jPanel12.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        sidebar.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_male_user_100px.png"))); // NOI18N
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel13.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        sidebar.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 580));

        contentbar.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(247, 247, 247));
        home.setEnabled(false);
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(96, 83, 150));
        jLabel9.setText("0");

        jPanel10.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        home.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 168, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(96, 83, 150));
        jLabel8.setText("Posts");
        home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 132, -1, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 83, 150));
        jLabel10.setText("Followers");
        home.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 132, -1, 29));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 83, 150));
        jLabel11.setText("0");

        jPanel9.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        home.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 168, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setText("0");

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        home.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 168, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 83, 150));
        jLabel13.setText("Following");
        home.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 132, -1, 29));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 83, 150));
        jLabel14.setText("Study Tip");
        home.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 172, -1, -1));

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 83, 150));
        jLabel16.setText("<html> Studying is good<br> Not studying is bad </html>");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        home.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 199, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 83, 150));
        jLabel2.setText("Name");
        home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 54, 407, 28));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(247, 247, 247));
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        home.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 258, 435, 122));

        jPanel8.setBackground(new java.awt.Color(96, 83, 150));

        btn_Close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Close.setForeground(new java.awt.Color(255, 255, 255));
        btn_Close.setText("X");
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(btn_Close)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Close, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        home.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 0, -1, -1));

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_refresh_25px.png"))); // NOI18N
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton1.setkBorderRadius(40);
        kButton1.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton1.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton1.setkStartColor(new java.awt.Color(247, 247, 247));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton1MousePressed(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        home.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 335, 33, -1));

        kButton3.setText("Create Post");
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton3.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton3.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton3.setkStartColor(new java.awt.Color(255, 136, 255));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton3MousePressed(evt);
            }
        });
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        home.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 521, 130, 40));

        kButton2.setText("View Post");
        kButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton2.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton2.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton2.setkStartColor(new java.awt.Color(232, 201, 232));
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton2MousePressed(evt);
            }
        });
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        home.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 340, 99, 40));

        kButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_delete_bin_25px.png"))); // NOI18N
        kButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton4.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton4.setkStartColor(new java.awt.Color(247, 247, 247));
        kButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton4MousePressed(evt);
            }
        });
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        home.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 335, 33, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(247, 247, 247));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(96, 83, 150));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("No post selected...");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setSelectionColor(new java.awt.Color(96, 83, 150));
        jScrollPane2.setViewportView(jTextArea1);

        home.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 387, 435, 191));

        contentbar.add(home, "card2");

        dashboard.setBackground(new java.awt.Color(247, 247, 247));
        dashboard.setEnabled(false);
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(247, 247, 247));
        jTable2.setRowHeight(50);
        jTable2.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        dashboard.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 435, 122));

        jPanel22.setBackground(new java.awt.Color(96, 83, 150));

        btn_Close1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Close1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Close1.setText("      X");
        btn_Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Close1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addComponent(btn_Close1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Close1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        dashboard.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 0, -1, -1));

        kButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_refresh_25px.png"))); // NOI18N
        kButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton6.setkBorderRadius(40);
        kButton6.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton6.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton6.setkStartColor(new java.awt.Color(247, 247, 247));
        kButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton6MousePressed(evt);
            }
        });
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        dashboard.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 33, -1));

        kButton7.setText("Follow");
        kButton7.setkBorderRadius(40);
        kButton7.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton7.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton7.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton7.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton7.setkStartColor(new java.awt.Color(255, 136, 255));
        kButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton7MousePressed(evt);
            }
        });
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        dashboard.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 30));

        kButton8.setText("View Post");
        kButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton8.setkBorderRadius(40);
        kButton8.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton8.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton8.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton8.setkStartColor(new java.awt.Color(232, 201, 232));
        kButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton8MousePressed(evt);
            }
        });
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        dashboard.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 99, 40));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(247, 247, 247));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(96, 83, 150));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("No post selected...");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setSelectionColor(new java.awt.Color(96, 83, 150));
        jScrollPane4.setViewportView(jTextArea2);

        dashboard.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 435, 191));

        jTextField1.setBackground(new java.awt.Color(247, 247, 247));
        jTextField1.setForeground(new java.awt.Color(96, 83, 150));
        jTextField1.setText("Search ");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        dashboard.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 186, 32));

        kButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_go_25px_1.png"))); // NOI18N
        kButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton5.setkBorderRadius(40);
        kButton5.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton5.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton5.setkSelectedColor(new java.awt.Color(153, 153, 255));
        kButton5.setkStartColor(new java.awt.Color(247, 247, 247));
        kButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton5MousePressed(evt);
            }
        });
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        dashboard.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 30, 40));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(96, 83, 150));
        jLabel31.setText("Select a friend to see their posts");
        dashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 29));

        kButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_find_user_male_25px.png"))); // NOI18N
        kButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton10.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton10.setkBorderRadius(40);
        kButton10.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton10.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton10.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton10.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton10.setkStartColor(new java.awt.Color(247, 247, 247));
        kButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton10MousePressed(evt);
            }
        });
        dashboard.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 33, 36));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_male_user_50px.png"))); // NOI18N
        dashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 50));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(96, 83, 150));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Name");
        dashboard.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 110, -1));

        jComboBox2.setForeground(new java.awt.Color(96, 83, 150));
        jComboBox2.setBorder(null);
        jScrollPane5.setViewportView(jComboBox2);

        dashboard.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 210, 30));

        jComboBox1.setForeground(new java.awt.Color(96, 83, 150));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jScrollPane6.setViewportView(jComboBox1);

        dashboard.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, -1));

        kButton12.setText("Unfollow");
        kButton12.setkBorderRadius(40);
        kButton12.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton12.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton12.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton12.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton12.setkStartColor(new java.awt.Color(255, 136, 255));
        kButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton12MousePressed(evt);
            }
        });
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        dashboard.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 30));

        contentbar.add(dashboard, "card3");

        profile.setBackground(new java.awt.Color(247, 247, 247));

        jTextField2.setBackground(new java.awt.Color(247, 247, 247));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("First name");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jTextField3.setBackground(new java.awt.Color(247, 247, 247));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Last name");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(231, 73, 134));
        jLabel23.setText("Profile");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Gender");

        jRadioButton1.setBackground(new java.awt.Color(247, 247, 247));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Female");
        jRadioButton1.setActionCommand("F");

        jRadioButton2.setBackground(new java.awt.Color(247, 247, 247));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Male");
        jRadioButton2.setActionCommand("M");

        kButton11.setText("Update");
        kButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kButton11.setkBorderRadius(40);
        kButton11.setkEndColor(new java.awt.Color(102, 183, 252));
        kButton11.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 51, 255));
        kButton11.setkHoverStartColor(new java.awt.Color(255, 222, 251));
        kButton11.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton11.setkStartColor(new java.awt.Color(255, 136, 255));
        kButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton11MousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(231, 73, 134));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_delete_35px.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_male_user_100px.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berana/breana.images/icons8_add_25px.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(profileLayout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profileLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton2)))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 212, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26))))
                    .addGroup(profileLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23))
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(profileLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(2, 2, 2)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );

        contentbar.add(profile, "card5");

        getContentPane().add(contentbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_CloseMouseClicked
    private void onHover(JPanel panel){
        panel.setBackground(new Color(232,201,232));
    }
     private void onLeaveHover(JPanel panel){
       panel.setBackground(Color.WHITE);
    }
    private void onClick(JPanel panel){
        panel.setBackground(new Color(205,136,205));
    }
    private void onLeaveClick(JPanel panel){
        panel.setBackground(Color.WHITE);
    }
   
//Left Panel Buttons:
    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        // TODO add your handling code here:
        onClick(Button1);
        onLeaveClick(Button2);
        onLeaveClick(Button3);
        onLeaveClick(Button4);
        cardLayout.show(contentbar,"card2");
    }//GEN-LAST:event_Button1MouseClicked

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        // TODO add your handling code here:
        onClick(Button2);
        onLeaveClick(Button1);
        onLeaveClick(Button3);
        onLeaveClick(Button4);
        cardLayout.show(contentbar,"card3");
        DashboardUser fol = new DashboardUser();
        jComboBox2.removeAllItems();
        fol.getFollowing(email, jComboBox2);
    }//GEN-LAST:event_Button2MouseClicked

    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseClicked
        // TODO add your handling code here:
        onClick(Button3);
        onLeaveClick(Button1);
        onLeaveClick(Button2);
        onLeaveClick(Button4);
        cardLayout.show(contentbar,"card5");
        UpdateUser uu = new UpdateUser();
        uu.fetchData(email);
        jTextField2.setText(uu.fname);
        jTextField3.setText(uu.lname);
        if(uu.gen.equals("M")){
            jRadioButton2.setSelected(true);
        }else{
            jRadioButton1.setSelected(true);
        }
    }//GEN-LAST:event_Button3MouseClicked

    private void Button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseClicked
        // TODO add your handling code here:
        onClick(Button4);
        onLeaveClick(Button1);
        onLeaveClick(Button2);
        onLeaveClick(Button3);
        Ulogin login = new Ulogin();
        login.show();
        view();
    }//GEN-LAST:event_Button4MouseClicked

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
        // TODO add your handling code here:
        onHover(Button1);
        onLeaveHover(Button2);
        onLeaveHover(Button3);
        onLeaveHover(Button4);
        
    }//GEN-LAST:event_Button1MouseEntered

    private void Button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseEntered
        // TODO add your handling code here:
        onHover(Button2);
        onLeaveHover(Button1);
        onLeaveHover(Button3);
        onLeaveHover(Button4);
             
    }//GEN-LAST:event_Button2MouseEntered

    private void Button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseEntered
        // TODO add your handling code here:
        onHover(Button3);
        onLeaveHover(Button1);
        onLeaveHover(Button2);
        onLeaveHover(Button4);
        
    }//GEN-LAST:event_Button3MouseEntered

    private void Button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseEntered
        // TODO add your handling code here:
        onHover(Button4);
        onLeaveHover(Button1);
        onLeaveHover(Button2);
        onLeaveHover(Button3);
        
    }//GEN-LAST:event_Button4MouseEntered

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
        // TODO add your handling code here:
       // onLeaveHover(Button1);
    }//GEN-LAST:event_Button1MouseExited

    private void Button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseExited
        // TODO add your handling code here:
       // onLeaveHover(Button2);
    }//GEN-LAST:event_Button2MouseExited

    private void Button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseExited
        // TODO add your handling code here:
        //onLeaveHover(Button3);
    }//GEN-LAST:event_Button3MouseExited

    private void Button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseExited
        // TODO add your handling code here:
      // onLeaveHover(Button4);
    }//GEN-LAST:event_Button4MouseExited

    private void kButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MousePressed
        input = true;
        refreshHome();
        jLabel16.setText(studyTips[new Random().nextInt(studyTips.length)]);
    }//GEN-LAST:event_kButton1MousePressed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton3MousePressed
        // TODO add your handling code here:
        UcreatePost newPost = new UcreatePost();
        newPost.show();
    }//GEN-LAST:event_kButton3MousePressed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton2MousePressed
        // TODO add your handling code here:
        int column = 0;
        int row = jTable1.getSelectedRow();
        tableValue = jTable1.getModel().getValueAt(row, column).toString();
        jTextArea1.setText(tableValue);
    }//GEN-LAST:event_kButton2MousePressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton4MousePressed
        // TODO add your handling code here:
        PopulatePostTable ps = new PopulatePostTable();
        ps.deletePost(email,tableValue);
        jTextArea1.setText("Post Deleted");
    }//GEN-LAST:event_kButton4MousePressed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton5MousePressed
        // TODO add your handling code here:
        followedEmail = (String) jComboBox2.getSelectedItem();
        DashboardUser du = new DashboardUser();
        du.populateTable(followedEmail, jTable2,input);
        du.getFollowedInfo(followedEmail);
        jLabel22.setText(du.followedName);
        PictureUser pu = new PictureUser();
        pu.getPicture(followedEmail, jLabel7);
    }//GEN-LAST:event_kButton5MousePressed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void btn_Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Close1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_Close1MouseClicked

    private void kButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton6MousePressed
        // TODO add your handling code here:
        input = true;
        DashboardUser du = new DashboardUser();
        du.populateTable(followedEmail, jTable2,input);
    }//GEN-LAST:event_kButton6MousePressed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton7MousePressed
        // TODO add your handling code here:
        String search = (String) jComboBox1.getSelectedItem();
        DashboardUser du = new DashboardUser();
        du.follow(email, search);
    }//GEN-LAST:event_kButton7MousePressed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton8MousePressed
        // TODO add your handling code here:
        int column = 0;
        int row = jTable2.getSelectedRow();
        tableValue = jTable2.getModel().getValueAt(row, column).toString();
        jTextArea2.setText(tableValue);
    }//GEN-LAST:event_kButton8MousePressed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton10MousePressed
        // TODO add your handling code here:
        String search = jTextField1.getText();
        DashboardUser searchItem = new DashboardUser();
        searchItem.searchUser(search, jComboBox1);
        //jComboBox1.setVisible(true);
        jScrollPane6.setVisible(true);
        kButton7.setVisible(true);
        DashboardUser fol = new DashboardUser();
        jComboBox2.removeAllItems();
        fol.getFollowing(email, jComboBox2);
    }//GEN-LAST:event_kButton10MousePressed
    int xx,yy;
    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_sidebarMouseDragged

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void kButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton12MousePressed
        // TODO add your handling code here:
        String ufollowedEmail = (String) jComboBox2.getSelectedItem();
        DashboardUser du = new DashboardUser();
        du.unfollow(email, ufollowedEmail);
    }//GEN-LAST:event_kButton12MousePressed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton12ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void kButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton11MousePressed
    String fname = jTextField2.getText(),lname = jTextField3.getText(),gender;
    gender = buttonGroup1.getSelection().getActionCommand();
    UpdateUser uu = new UpdateUser();
    uu.update(email, fname, lname, gender);
    
    
        

    }//GEN-LAST:event_kButton11MousePressed

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel26MousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
        File selectedfile=file.getSelectedFile();
        path=selectedfile.getAbsolutePath();
        s=path;
        ImageIcon myimage=new ImageIcon(s);
        Image img=myimage.getImage();
        Image newimg=img.getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newimg);
        jLabel6.setIcon(image);
        jLabel15.setIcon(image);
        PictureUser pu = new PictureUser();
        pu.addPicture(email, s);
        
        }
    }//GEN-LAST:event_jLabel25MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel Button2;
    private javax.swing.JPanel Button3;
    private javax.swing.JPanel Button4;
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Close1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentbar;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel home;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton7;
    private keeptoo.KButton kButton8;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
